### ISSUE TITLE
Share file in Clothing1M

### ISSUE THREAD

**Issue by devinxzhang** [tmllab/Me-Momentum#1]
Hi,

Thanks for your interesting work. I would like to try your method but there is an unknown file named "share.txt" in "ClothingData.py". This file seems to be not provided by the original Clothing1M dataset. Could you please provide it? Thanks!

**Comment by tmllab** [comment]
Thanks for your interest.  "share.txt"  was not used in the training process, so we will delete it from the codes later.

BTW, we generated "share.txt" by comparing label files, where some images are given in both files. Here is the file we used.

[share.txt](https://github.com/tmllab/Me-Momentum/files/8131884/share.txt)
